name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This job uses a fancy tool to extract a secret file, and forwards it to the next step
  extract:
    name: Extract the secret file
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Unzip the secret file
      - name: Extract the super secret file
        run: |
          echo What was Donald Trumps super secret twitter password?
          7z x secret.7z -p${{ secrets.SUPER_SECRET_7Z_PASSWORD }}
          mkdir artifacts
          cp this_file_is_secret.md artifacts/
      # Upload unzipped secret file
      - uses: actions/upload-artifact@master
        with:
          name: artifacts-${{ github.workflow }}
          path: artifacts

  # This job uses the extracted secret file on windows
  print_windows:
    name: Use artifact on Windows
    needs: [extract]
    runs-on: windows-latest
    timeout-minutes: 2
    steps:
      - name: Download extracted secret
        uses: actions/download-artifact@master
        with:
          name: artifacts-${{ github.workflow }}
          path: secrets

      - name: Print the super secret file
        run: |
          cat secrets/this_file_is_secret.md

  # This job uses the extracted secret file on macos
  print_macos:
    name: Use artifact on macos
    needs: [extract]
    runs-on: macos-latest
    timeout-minutes: 2
    steps:
      - name: Download extracted secret
        uses: actions/download-artifact@master
        with:
          name: artifacts-${{ github.workflow }}
          path: secrets

      - name: Print the super secret file
        run: |
          echo ${{ secrets.SUPER_SECRET_7Z_PASSWORD }}
          cat secrets/this_file_is_secret.md
  # Celebrate success on all platforms
  yay:
    name: Celebrate success
    needs: [print_windows, print_macos]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Yay
        run: echo Yay!!

  # End of this workflow